# Generated by Django 3.2 on 2022-08-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editora', '0001_initial'),
        ('escritor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('paginas', models.PositiveIntegerField(default=0)),
                ('editora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='editora.editora')),
                ('escritor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='escritor.escritor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
